### ISSUE TITLE
Unix syntax after starting docker container fails on Windows

### ISSUE THREAD

**Issue by anineharto** [acntech/fruit-classifier#40]
Running the following command
`docker exec -i -t docker_fruit_classifier_1 /bin/bash`

Produces error message
`OCI runtime exec failed: exec failed: container_linux.go:345`

**Workaround**
`docker exec -i -t docker_fruit_classifier_1 bash`

**Comment by loeiten** [comment]
See for example https://stackoverflow.com/a/48835704/2786884 for details
